version: "3.9"
services:
  api:
    build: .
    container_name: simpleblog_api
    depends_on:
      - sqlserver
    environment:
      - SQLSERVER_CONNECTION_STRING=Server=sqlserver;Database=SimpleBlogDb;User=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - simpleblog_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: simpleblog_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    networks:
      - simpleblog_network
    volumes:
      - sqldata:/var/opt/mssql

networks:
  simpleblog_network:

volumes:
  sqldata:
